server:
  port: 8764
spring:
  application:
    name: service-logistic
  zipkin:
    base-url: http://zipkin-server:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/